### 第 1 题： 正态分布

设 $X \sim N(2, 3^{2})$ ， 求：

1. $0<X<5$ 的概率
2. $X$ 0.025 右侧分位点
3. 画出其概率密度曲线和累计分布函数曲线

from scipy import stats
import matplotlib.pyplot as plt #不是xyplot而是pyplot！！！
import numpy as np

##（1）
rv = stats.norm(2,3)
P = rv.cdf(5)-rv.cdf(0);P

##（2）
XU = -rv.ppf(0.025);XU

##(3)
x = np.linspace(-3,3,100)
plt.plot(x,stats.norm.pdf(x),label = 'norm pdf') #概率密度曲线
plt.plot(x,stats.norm.pdf(x).cumsum(),label = 'norm pdf') #累积

### 第 2 题： 卡方分布

设 $X \sim \chi^{2}(5)$ ， 求：
1. $1<X<5$ 的概率
2. $X$ 0.025 右侧分位点
3. 画出其概率密度曲线和累计分布函数曲线

##(1)
rv = stats.chi2(5)
P = rv.cdf(5);P

##(2)
XU = rv.ppf(0.025);XU

##(3)
x = np.linspace(0,10,100)
plt.plot(x,stats.chi2.pdf(x,df=5),label='chi2 pdf') #概率密度曲线
plt.plot(x,stats.chi2.pdf(x,df=5).cumsum(),label = 'chi2 pdf')#绘制累积概率密度函数
#plt.fill_between(np.linspace(0,20,100),stats.chi2.pdf(np.linspace(0,20,100),df=4),alpha=0.15) #填充曲线


### 第 3 题： 二项分布

设 $X \sim B(10, 0.3)$ ， 求：

1. $X=3$ 的概率
2. $X$ 0.025 右侧分位点
3. 画出其概率分布率图和累计分布函数曲线

##(1)
rv = stats.binom(10, 0.3)
P = rv.cdf(3);P

##(2)
XU = rv.ppf(0.025);XU

##(3)
#
x = np.arange(stats.binom.ppf(0.01, 10, 0.3), stats.binom.ppf(0.99, 10, 0.3))
fig, ax = plt.subplots(1, 1)
mean,var,skew,kurt = stats.binom.stats(10,0.3,moments='mvsk')
x = np.arange(stats.binom.ppf(0.01,10,0.3), stats.binom.ppf(0.99,5,0.4))
ax.plot(x,stats.binom.pmf(x, 10, 0.3),'bo',ms=8,label='binom pmf')
ax.vlines(x,0,stats.binom.pmf(x, 10, 0.3),colors='b',lw=5,alpha=0.5)
ax.vlines(x,0,rv.pmf(x),colors='k',linestyles='-',lw=1,label='frozen pmf')
ax.legend(loc='best',frameon=False)
plt.show()


fig, ax = plt.subplots(1, 1)
mean,var,skew,kurt = stats.binom.stats(10,0.3,moments='mvsk')
x = np.arange(stats.binom.ppf(0.01,10,0.3), stats.binom.ppf(0.99,5,0.4))
ax.plot(x,stats.binom.pmf(x, 10, 0.3).cumsum(),'bo',ms=8,label='binom pmf')
ax.vlines(x,0,stats.binom.pmf(x, 10, 0.3).cumsum(),colors='b',lw=5,alpha=0.5)
rv = stats.binom(10, 0.3)
ax.vlines(x,0,rv.pmf(x).cumsum(),colors='k',linestyles='-',lw=1,label='frozen pmf')
ax.legend(loc='best',frameon=False)
plt.show()







### 第 4 题： 核密度估计

设 $X \sim N(2, 3^{2})$ ， 求：

1. 生成1000个随机数字（np.random)
2. 使用核方法估计随机数字的密度函数并画出其曲线
3. 添加 $X \sim N(2, 3^{2})$ 的密度曲线

##(1)
x = np.random.normal(2,3,1000)

##(2)
from sklearn.neighbors.kde import KernelDensity
import numpy as np
y = stats.norm.pdf(x)
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
kde = KernelDensity(kernel='gaussian', bandwidth=0.2).fit(x,y)
kde.score_samples(x)

array([-0.41075698, -0.41075698, -0.41076071, -0.41075698, -0.41075698,
       -0.41076071])


import org.apache.spark.mllib.stat.KernelDensity

val_sample = sc.parallelize(x)
val kd = new KernelDensity()
  .setSample(sample)
  .setBandwidth(3.0)
val densities = kd.estimate(Array(-1.0, 2.0, 5.0))


